export const GET_GENREFANCYITEMS = 'GET_GENREFANCYITEM';
export const GET_FANCYITEMDETAILS = 'GET_FANCYITEMDETAILS';
export const SET_CURRENTGENRE = 'SET_CURRENTGENRE';
export const SET_LOADING = 'SET_LOADING';
